name: Manual-Trigger Spec Build

on:
  push:
    branches: [main]
  workflow_dispatch: # Adds a "Run workflow" button in GitHub UI

jobs:
  prepare-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout UBC Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install and build with Bikeshed
        run: |
          pip install bikeshed
          bikeshed update
          bikeshed spec index.bs index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
